version: '3'
services:
  camel-app:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
  mq-msg:
    image: "webcenter/activemq:latest"
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'camelDb'
