spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camelDb
    username: user
    password: password
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    packages.trust-all: true
  mongodb:
    host: localhost
    port: 27017
    authenticationDatabase: admin
    username: root
    password: example
    database: camel_demo

logging:
  level:
    org.apache.camel: DEBUG

server:
  port: 8080

account:
  consul:
      domain: localhost
      self-domain: localhost
      start: http://${account.consul.domain}:8500/v1/agent/service/register
      stop: http://${account.consul.domain}:8500/v1/agent/service/deregister
  server:
    port: 8083

camel:
  springboot:
    name: ServicesRest
    main-run-controller: true
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
api:
  path: '/camel'

sqlRoute: jdbc:dataSource
loggingPostRoute: direct:loggingPostRoute
secondLevelPostRoute: direct:secondLevelPostRoute
processMQMessageRoute: direct:processMQMessageRoute
errorQueue: activemq:errorItemQueue
toRoute: jdbc:dataSource
selectNode: sql:select * from input_posts where id =:#id limit 1?dataSource=#dataSource
selectCountryNode: sql:select * from country where country_code=:#countryId?dataSource=#dataSource
restEndpointRoute: http://localhost:8082/country
restClientTimerRoute: timer:restRoute?period=60s
restClient: direct:restClient
dbNode: jdbc:dataSource
writeMQRoute: direct:writeQueue
mqDummyReadRoute: direct:mqDummyReadRoute
getAllMongoDBRoute: direct:getAllMongoDBRoute
getAllRequest: mongodb:mongodb?database=camel_demo&collection=input_posts&operation=findAll
mongoDbBeanConversionRoute: direct:mongoDbBeanConversionRoute

mongo:
  postRoute: direct:postRoute
  insertInputPost: mongodb:mongodb?database=camel_demo&collection=input_posts&operation=insert
  getByIdRoute: direct:getByIdRoute
  getByIdMongo: mongodb:mongodb?database=camel_demo&collection=input_posts&operation=findOneByQuery
  putByIdRoute: direct:putByIdRoute
  putByIdMongo: mongodb:mongodb?database=camel_demo&collection=input_posts&operation=update
  deleteByIdRoute: direct:deleteByIdRoute
  deleteByIdMongo: mongodb:mongodb?database=camel_demo&collection=input_posts&operation=remove
---
spring:
  profiles: CI-DEV
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/camelDb
    username: user
    password: password
  activemq:
    brokerUrl: tcp://mq-msg:61616
    user: admin
    password: admin

account:
  consul:
    self-domain: camel-app
    domain: consul
  server:
    port: 8083